version: '3.3'

services:

  db:
    image: mariadb:10.4
    restart: on-failure
    environment:
      MYSQL_DATABASE: testdb
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql
      - wordpress:/var/www/html

  wordpress:
    depends_on:
      - db
    build:
      context: ./bin/docker/wordpress
    ports:
      - 8084:80
    image: wordpress:latest
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: testdb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_DEBUG: 'true'
    volumes:
      - ../uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ../gutenberg-examples:/var/www/html/wp-content/plugins/gutenberg-examples
      - ../spine-app:/var/www/html/wp-content/plugins/spine-app
      - ../log-debug:/var/www/html/wp-content/plugins/log-debug
      - ./:/var/www/html/wp-content/plugins/woocommerce-gutenberg-products-block-master
      - ../wordpress:/var/www/html

  wordpress-cli:
    depends_on:
      - db
      - wordpress
    build:
        context: ./bin/docker/wp-cli
    restart: on-failure
    environment:
        WORDPRESS_HOST: db:3306
        WORDPRESS_TITLE: ACF Test
        WORDPRESS_LOGIN: admin
        WORDPRESS_PASSWORD: example
        WORDPRESS_PORT: 8084
        WORDPRESS_EMAIL: info@webpremiere.dev
        DOMAIN_NAME:

volumes:
  db: {}
  wordpress: {}
